#!/bin/bash
export THEMEPATH="$( cd "$(dirname "$0")" ; pwd -P )"
leftwm-command "LoadTheme $THEMEPATH/theme.ron"
feh --bg-scale "${THEMEPATH}/bg.png"
switchMonitors # I have a very weird monitor config with my main monitor on the right 
polybar main
